fix leak in LS::Service move assignment
:Release Notes:
Removed some resources leak

:Detailed Notes:
- added integration test for LS::Service
- fixed leak in LS::Service move assignment
- fixed run_with_hub
- added tests for BHV-4680 and BHV-4681

:Testing Performed:
unit and integration tests on desktop

:QA Notes:

:Issues Addressed:
[BHV-1589] Implement category registration with its description
[BHV-4680] LS2: doesn't send error responses after static service register/unregister
[BHV-4681] LS2: LSCallSetTimeout logic doesn't notify client about canceling call due to timeout

Open-webOS-DCO-1.0-Signed-off-by: Nikolay Orliuk <nikolay.orliuk@lge.com>

Change-Id: I55f5dc5acd0a956c499f439d73b5109a0443aec2
Reviewed-on: https://g2g.palm.com/5286
Reviewed-by: DCO Verification
Reviewed-by: Nikolay Orliuk <nikolay.orliuk@lge.com>
Tested-by: Nikolay Orliuk <nikolay.orliuk@lge.com>
Reviewed-by: Anatolii Sakhnik <anatolii.sakhnik@lge.com>

diff --git a/src/libluna-service2/test/run_with_hub b/src/libluna-service2/test/run_with_hub
--- a/src/libluna-service2/test/run_with_hub
+++ b/src/libluna-service2/test/run_with_hub
@@ -161,9 +161,6 @@ END
 		install_role $service_exe pub ${role_pub[$service]}
 		install_role $service_exe prv ${role_prv[$service]}
 	done
-
-	cat $conf_root/var/palm/ls2/services/prv/com.palm.test_service.service
-	exit 0
 }
 
 install_files
@@ -197,6 +194,12 @@ spawn_hubd()
 	hub_pids+=($!)
 }
 
+# drop artifacts from prev. runs (not always we have clean shutdown)
+[ -S /tmp/com.palm.public_hub ] && rm /tmp/com.palm.public_hub
+[ -S /tmp/com.palm.private_hub ] && rm /tmp/com.palm.private_hub
+killall -KILL ls-hubd
+# TODO: introduce special ENV variable or config that will redirect from /tmp to any other folder
+
 spawn_hubd private
 spawn_hubd public
 
@@ -204,14 +207,13 @@ while [[ ! -S /tmp/com.palm.private_hub || ! -S /tmp/com.palm.public_hub ]]; do
 	sleep 0.1
 done
 
-(
 for service in ${services_to_spawn[@]}; do
 	echo "Launching $service"
 	$service &
+	[[ $? -eq 0 ]] || die "Failed to start $service"
 	service_pid+=($!)
 done
 for pid in ${service_pid[@]}; do
 	wait $pid
 	[[ $? -eq 0 ]] || die "Failure detected"
 done
-)
